### ISSUE TITLE
Better documentation or bug?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tinymce_snippets#3]
I'm trying to get this module to work. I'm not 100% certain I know what it is supposed to do, but I think it's allows you to create some preformatted snippets of text that can be inserted into a text field using TinyMCE. 

I've enabled the module and created two text snippets, but I can not figure out how to use or access them. I expect that there will be a snippets option under the "insert" feature, but I'm not finding it there. 

I'm usure if I'm just not understanding this module correctly or if there might be a bug?

I have two cute snippets.
![image](https://github.com/backdrop-contrib/tinymce_snippets/assets/3144571/8f7afc92-11d5-4538-a3d9-cfa7cfc24e58)

I expected to find a snippets option here:
![image](https://github.com/backdrop-contrib/tinymce_snippets/assets/3144571/e8fc5fca-be7c-49ad-9715-ef19ceea10e4)

Is it me or is something not working?

Tested using the latest dev branch of Backdrop CMS and TinyMCE and Snippets module downloaded with project browser. (latest official release)

**Comment by indigoxela** [comment]
@stpaultim many thanks for reporting. Yes, that needs a little more documentation.

It won't be part of the menu automatically.
The easiest way would be to add the icon to the toolbar, which will also load the plugin in the editor.

![add-snippet-icon](https://github.com/backdrop-contrib/tinymce_snippets/assets/842066/3352ef1e-efa0-4467-8c84-79f8e7111f5c)

You can also adapt the whole menu contents, but that would be more effort.

**Comment by stpaultim** [comment]
Confirmed. Sorry, I should have figured that out. 

But, adding a note to this effect in the README would be good.

**Comment by stpaultim** [comment]
I saw the change to the Readme file. Thank you. I'll close this ticket as "Fixed."
